### ISSUE TITLE
Do we have a hook for this plugin to be deactivated in a certain page

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/wp-native-php-sessions#110]
There are times that this plugin conflicts with another plugin and users want to simply disable this plugin in a certain url, do we have a hook for that?

**Comment by adamedgmond** [comment]
Barring an available hook, you can use some code like this or a plugin like Plugin Organizer:

https://gist.github.com/carlodaniele/5b8343dd17a64c69d04459bffad2312c

**Comment by danielbachhuber** [comment]
Hi @carl-alberto,

Thanks for the issue. There isn't a hook for the scenario you're describing. I'm not sure it makes sense to formally support in the plugin either. A code snippet similar to @adamedgmond's Gist should the trick, with one of two approaches:

1. Filter the `active_plugins` option for specific requests.
2. Load WP Native PHP Sessions from a mu-plugin, instead of activating it as a plugin, and have it load conditionally based on the request.

Hope this helps!

**Comment by carl-alberto** [comment]
Thanks for the inputs @adamedgmond @danielbachhuber!
