### ISSUE TITLE
[question] Can this be used for guest/anonymous users?

### ISSUE THREAD

**Issue by nicomollet** [pantheon-systems/wp-native-php-sessions#196]
Hello

I found this project, after discovering how sessions work in WP.

My projects needs to authenticate customers with another database/API, but customers would not have a WordPress account and still be guests users (user_id=0).

My firsts tests show that anonymous users share the same session data, and that's obsviously not what I want.

Can somebody confirm it is possible or not to save session data for anonymous users?
Thank you

PS: Not sure that matters but I am hosted on Kinsta.

**Comment by danielbachhuber** [comment]
Hey @nicomollet,

Thanks for the question 😄 

WP Native PHP Sessions integrates with PHP's native session management functionality. It provides an alternate storage mechanism for session data, while otherwise depending 100% on PHP for session management.

Anonymous users should have their session data stored separately by default. If the data is getting combined, there's probably some issue with your server configuration, etc.

Hope this helps!
